### ISSUE TITLE
Problem with building some icons

### ISSUE THREAD

**Issue by yoricya** [wavy-cat/Cat-Activity#2]
![image](https://github.com/user-attachments/assets/2918aed1-64a0-4a36-9c82-c4f677b71114)
Предлагаю добавить иконку VLang 
![image](https://s.yoricya.ru/silly)

**Comment by wavy-cat** [comment]
Он есть
https://github.com/wavy-cat/Cat-Activity/blob/master/src%2Fmain%2Fkotlin%2Fcat%2Fwavy%2Fcatactivity%2Ftypes%2FFileType.kt#L241

Проблема может быть на стороне серверов Cloudflare или Discord. Попробуй изменить цветовую тему иконок

**Comment by yoricya** [comment]
Будто на сервере нету файла с иконкой, либо действительно у клоуда проблема
![Снимок экрана 2024-12-21 в 23 12 35](https://github.com/user-attachments/assets/1f00fb50-c5f7-4b6e-91ab-89b79760f661)
![Снимок экрана 2024-12-21 в 23 15 08](https://github.com/user-attachments/assets/6c3454f0-02a3-4191-91bb-bf9fa28d4a84)

**Comment by wavy-cat** [comment]
Хм... действительно, из Cloudflare Dashboard видно, что иконка языка V не была загружена.
![image](https://github.com/user-attachments/assets/15f705e8-826d-4031-8d2d-199866c22745)

Однако, в файле иконок для сборки V, последнего коммита, по которому [был запущен Action со сборкой](https://github.com/wavy-cat/Cat-Activity/actions/runs/11756059337), присутствует V
https://github.com/wavy-cat/Cat-Activity/blob/91d2dad51ed134e9b801ac9979ec5c3259d5d2a7/generate/icons.json#L233

Судя по артефактам сборки, было отрендерено 725 файлов из 1148 (по формуле: `4 темы * (253 иконок языков и технологий + 17 иконок ide * 2 варианта: старые и новые )`.

И... да, это ошибка во время сборки (traceback примерно с [4276 строки логов слоя *Run generate.py*](https://github.com/wavy-cat/Cat-Activity/actions/runs/11756059337/job/32751803863#step:6:4277)), однако интересно, что workflow не падает и завершается без ошибки.
Я могу пометить это как баг, однако я планирую в ближайшее время доработать эту часть, переписав на TypeScript и тем самым позволив получать список иконок прямиком из TS конфига Catppuccin и реализовав прочие удобные вещи, так что думаю что эта проблема решиться с приходом нового сборщика.

**Comment by wavy-cat** [comment]
Если хочешь, можешь отправить PR с исправлением проблемы в текущей версии сборщика

**Comment by yoricya** [comment]
Ну, с PR я наверно не разберусь поэтому буду ждать, но, спасибо за обратную связь
